apiVersion: v1
kind: Secret

metadata:
  name: mysql-secrets

type: Opaque

stringData:
  MYSQL_DATABASE: "laravel"
  MYSQL_USER: "laravel"
  MYSQL_PASSWORD: "your_password"
  MYSQL_ROOT_PASSWORD: "your_root_password"