apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: laravel-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: laravel-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: laravel-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: laravel-cluster-role
  apiGroup: rbac.authorization.k8s.io